services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: seduce
      POSTGRES_PASSWORD: seduce_secret
      POSTGRES_DB: seduce_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
